sudo: false
language: python
python:
- '3.5'
script:
- ./waf configure clean build dist
- pushd build
- md5sum "script.module.backports.shutil_which-3.5.1.zip" > "script.module.backports.shutil_which-3.5.1.zip.md5"
- popd
before_deploy:
- mkdir -p dist/
- cp build/*.zip build/*.zip.md5 addon.xml icon.png dist/
deploy:
- provider: s3
  access_key_id: "${AWS_KEY_ID}"
  secret_access_key: "${AWS_ACCESS_KEY}"
  bucket: xbmc.beardypig.plugins
  local-dir: dist
  upload-dir: addons/script.module.backports.shutil_which
  skip_cleanup: true
  on:
    repo: beardypig/script.module.backports.shutil_which
    tags: true
- provider: releases
  api_key: "${GITHUB_API_KEY}"
  file: $TRAVIS_BUILD_DIR/build/script.module.backports.shutil_which-$TRAVIS_TAG.zip
  on:
    repo: beardypig/script.module.backports.shutil_which
    tags: true
after_deploy:
- gem install travis
- curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
- sh trigger-travis.sh beardypig xbmc.beardypig.plugins $TRAVIS_ACCESS_TOKEN
